# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 42) do

  create_table "blogs", :force => true do |t|
    t.column "url",                :string
    t.column "rss",                :string
    t.column "author",             :string
    t.column "avatar",             :string
    t.column "comment_expression", :string
    t.column "restricted",         :boolean
  end

  create_table "configurations", :force => true do |t|
    t.column "name",  :string
    t.column "value", :string
  end

  add_index "configurations", ["name"], :name => "index_configurations_on_name"

  create_table "forums", :force => true do |t|
    t.column "name",         :string
    t.column "description",  :string,  :limit => 999
    t.column "topics_count", :integer,                :default => 0
    t.column "posts_count",  :integer,                :default => 0
    t.column "position",     :integer
  end

  create_table "karmas", :force => true do |t|
    t.column "user_id",    :integer
    t.column "post_id",    :integer
    t.column "value",      :integer
    t.column "created_at", :datetime
  end

  add_index "karmas", ["post_id"], :name => "index_karmas_on_post_id"
  add_index "karmas", ["user_id"], :name => "index_karmas_on_user_id"
  add_index "karmas", ["user_id", "post_id"], :name => "index_karmas_on_user_id_and_post_id", :unique => true

  create_table "moderatorships", :force => true do |t|
    t.column "forum_id", :integer
    t.column "user_id",  :integer
  end

  create_table "pg_ts_cfg", :id => false, :force => true do |t|
    t.column "ts_name",  :text, :null => false
    t.column "prs_name", :text, :null => false
    t.column "locale",   :text
  end

  create_table "pg_ts_cfgmap", :id => false, :force => true do |t|
    t.column "ts_name",   :text,   :null => false
    t.column "tok_alias", :text,   :null => false
    t.column "dict_name", :string
  end

  create_table "phrases", :force => true do |t|
    t.column "text",    :string
    t.column "user_id", :integer
  end

  create_table "posts", :force => true do |t|
    t.column "user_id",          :integer
    t.column "topic_id",         :integer
    t.column "body",             :text
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "forum_id",         :integer
    t.column "good_karma_count", :integer,  :default => 0
    t.column "bad_karma_count",  :integer,  :default => 0
  end

  add_index "posts", ["forum_id"], :name => "index_posts_on_forum_id"
  add_index "posts", ["topic_id"], :name => "index_posts_on_topic_id"
  add_index "posts", ["user_id"], :name => "index_posts_on_user_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
    t.column "user_id",    :integer
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"
  add_index "sessions", ["user_id"], :name => "index_sessions_on_user_id"
  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "topics", :force => true do |t|
    t.column "forum_id",    :integer
    t.column "user_id",     :integer
    t.column "title",       :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "hits",        :integer,  :default => 0
    t.column "sticky",      :integer,  :default => 0
    t.column "posts_count", :integer,  :default => 0
    t.column "replied_at",  :datetime
  end

  add_index "topics", ["forum_id"], :name => "index_topics_on_forum_id"
  add_index "topics", ["user_id"], :name => "index_topics_on_user_id"

  create_table "users", :force => true do |t|
    t.column "login",                :string
    t.column "email",                :string
    t.column "password",             :string
    t.column "created_at",           :datetime
    t.column "last_login_at",        :datetime
    t.column "admin",                :boolean
    t.column "posts_count",          :integer,  :default => 0
    t.column "last_seen_at",         :datetime
    t.column "display_name",         :string
    t.column "updated_at",           :datetime
    t.column "aim",                  :string
    t.column "yahoo",                :string
    t.column "google_talk",          :string
    t.column "msn",                  :string
    t.column "website",              :string
    t.column "login_key",            :string
    t.column "login_key_expires_at", :datetime
    t.column "avatar",               :string
    t.column "good_karma_count",     :integer,  :default => 0
    t.column "pass_ok",              :integer,  :default => 0
  end

end
